document_management_system/document_management_system/accounts/urls.py
from django.urls import path,include
from django.contrib.auth import views as auth_views
from .forms import PwdResetConfirmForm, PwdResetForm
from django.views.generic import TemplateView
from .views import (
    deshboard_page_view,
    employee_register_view,
    manager_register_view,
    user_login_view,
    user_logout_view,
    all_user_view,
    register_all_view,
    user_update_view,
    user_delete_view,
    user_profile_update,
    user_profile_view,
)

app_name = 'accounts'
urlpatterns = [
    path('dashboard/', deshboard_page_view, name='dashboard_view'),
    path('register-all_view/', register_all_view, name='register_all_view'),
    path('register/', employee_register_view, name='register_view'),
    path('manager-register/', manager_register_view, name='manager_register_view'),
    path('login/', user_login_view, name='login_view'),
    path('logout/', user_logout_view, name='logout_view'),
    path('all-user/', all_user_view, name='all_user_view'),
    path('user-update/<int:pk>/', user_update_view, name='user_update_view'),
    path('user-delete/<int:pk>/', user_delete_view, name='user_delete'),
    path('user-update/<int:pk>/', user_update_view, name='user_update_view'),
    path('user-delete/<int:pk>/', user_delete_view, name='user_delete'),


    # password reset
    path(
        "password_reset/",
        auth_views.PasswordResetView.as_view(
            template_name="account/password_reset/password_reset_form.html",
            success_url="password_reset_email_confirm",
            email_template_name="account/password_reset/password_reset_email.html",
            form_class=PwdResetForm,
        ),
        name="pwdreset",
    ),
    path(
        "password_reset_confirm/<uidb64>/<token>",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="account/password_reset/password_reset_confirm.html",
            success_url="password_reset_complete/",
            form_class=PwdResetConfirmForm,
        ),
        name="password_reset_confirm",
    ),
    path(
        "password_reset/password_reset_email_confirm/",
        TemplateView.as_view(template_name="account/password_reset/reset_status.html"),
        name="password_reset_done",
    ),
    path(
        "password_reset_confirm/Mg/password_reset_complete/",
        TemplateView.as_view(template_name="account/password_reset/reset_status.html"),
        name="password_reset_complete",
    ),
]

document_management_system/document_management_system/core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('accounts.urls', namespace='account')),
    path('', include('documents.urls', namespace='document')),
   

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

'''
template_name='account/password_reset.html'
template_name='account/password_reset_done.html'
template_name='account/password_reset_confirm.html'
template_name='account/password_reset_complete.html'
path('password_change/', auth_views.PasswordChangeView.as_view(),
        name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(),
        name='password_change_done'),

    path('password_reset/', auth_views.PasswordResetView.as_view(),
        name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(),
        name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),
        name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(),
        name='password_reset_complete'),
'''

document_management_system/document_management_system/documents/urls.py
from django.urls import path
from documents.views import (
    LandingView,
    public_document_view,
    private_document_view,
    user_create_document_view,
    employee_document_view,
    create_group_assignment,
    group_assignment_list,
    employee_group_assignment,
    update_document_view,
    AllDocumentView,
    delete_document_view,
    delete_group_assignment,
    update_group_assignment,
    search_view,
)

app_name = 'documents'
urlpatterns = [
    path('', LandingView.as_view(), name='home'),
    path('all-document/', AllDocumentView.as_view(), name='all_document'),
    path('create-document/', user_create_document_view, name='create_document_view'),
    path('public-document/', public_document_view, name='public_document'),
    path('private-document/', private_document_view, name='private_document'),
    path('document/', employee_document_view, name='document_view'),
    path('create-group-assignment/', create_group_assignment, name='group_assignment_view'),
    path('group-assignment-list/', group_assignment_list, name='group_assignment_list_view'),
    path('employee-assignment/', employee_group_assignment, name='employee_assignment_view'),
    path('update-document/<int:pk>/', update_document_view, name='update_document_view'),
    path('delete-document/<int:pk>/', delete_document_view, name='delete_document'),
    path('delete-group-assignment/<slug:slug>/', delete_group_assignment, name='delete_group_assigment'),
    path('update-group-assignment/<slug:slug>/', update_group_assignment, name='update_group_assignment'),
     path('search/', search_view, name='search_view'),
]

document_management_system/document_management_system/templates/snippets/footer.html
<footer class="footer">
    <div class="container-fluid">
        <div class="row text-muted">
            <div class="col-6 text-left">
                <p class="mb-0">
                    <a href="/" class="text-muted"><strong>@plan International</strong></a> &copy;
                </p>
            </div>
            <div class="col-6 text-right">
                <ul class="list-inline">
                    <li class="list-inline-item">
                        <a class="text-muted" href="#">Support</a>
                    </li>
                    <li class="list-inline-item">
                        <a class="text-muted" href="#">Help Center</a>
                    </li>
                    <li class="list-inline-item">
                        <a class="text-muted" href="#">Privacy</a>
                    </li>
                    <li class="list-inline-item">
                        <a class="text-muted" href="#">Terms</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</footer>

document_management_system/document_management_system/templates/snippets/home-navbar.html
{% load static %}
<nav class="navbar navbar-expand navbar-light navbar-bg">

    <div class="navbar-collapse collapse container">
        <ul class="navbar-nav">
            <li class="nav-item"><a class="nav-link active" href="#">DCMS</a></li>
            
        </ul>
        <ul class="navbar-nav navbar-align">
            <ul class="navbar-nav navbar-align">
                {% if request.user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-icon dropdown-toggle d-inline-block d-sm-none" href="#" data-toggle="dropdown">
                        <i class="align-middle" data-feather="settings"></i>
                    </a>

                    <a class="nav-link dropdown-toggle d-none d-sm-inline-block" href="#" data-toggle="dropdown">
                        <img src="{% static 'img/avatars/avatar.jpg' %}" class="avatar img-fluid rounded mr-1"
                            alt="Welcome" />
                            <span class="text-dark">{{ user.username }}  </span>
                    <div class="dropdown-menu dropdown-menu-right">
                        <a class="dropdown-item" href="{% url 'account:dashboard_view' %}"><i class="align-middle mr-1"
                                data-feather="user"></i> Dashboard</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'account:logout_view' %}">Log out</a>
                    </div>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'account:register_all_view' %}">Register</a>
                </li>
                <li class="nva-item">
                    <a class="nav-link" href="{% url 'account:login_view' %}">Login</a>
                </li>
                {% endif %}
            </ul>
    </div>
</nav>

document_management_system/document_management_system/templates/snippets/navbar.html
{% load static %}
<nav class="navbar navbar-expand navbar-light navbar-bg">
    <a class="sidebar-toggle d-flex">
        <i class="hamburger align-self-center"></i>
    </a>

    <form action="{% url 'document:search_view' %}" method="GET" class="form-inline d-none d-sm-inline-block">
        <div class="input-group input-group-navbar">
            <input type="text" class="form-control" name="q" placeholder="Search…" aria-label="Search">
            <div class="input-group-append">
                <button class="btn" type="submit">
                    <i class="align-middle" data-feather="search"></i>
                </button>
            </div>
        </div>
    </form>

    <div class="navbar-collapse collapse">
        <ul class="navbar-nav navbar-align">
            <ul class="navbar-nav navbar-align">

                
                {% if request.user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-icon dropdown-toggle d-inline-block d-sm-none" href="#" data-toggle="dropdown">
                        <i class="align-middle" data-feather="settings"></i>
                    </a>

                    <a class="nav-link dropdown-toggle d-none d-sm-inline-block" href="#" data-toggle="dropdown">
                        <img src="{% static 'img/avatars/avatar.jpg' %}" class="avatar img-fluid rounded mr-1"
                            alt="Welcome" />
                        <span class="text-dark">{{ user.username }} </span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right">
                        <a class="dropdown-item" href="{% url 'account:dashboard_view' %}"><i class="align-middle mr-1"
                                data-feather="user"></i> Dashboard</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'account:logout_view' %}">Log out</a>
                    </div>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'account:register_view' %}">Register</a>
                </li>
                <li class="nva-item">
                    <a class="nav-link" href="{% url 'account:login_view' %}">Login</a>
                </li>
                {% endif %}
            </ul>
    </div>
</nav>

document_management_system/document_management_system/templates/snippets/sidebar-navbar.html
<nav id="sidebar" class="sidebar">
    <div class="sidebar-content js-simplebar">
        <a class="sidebar-brand" href="index.html">
            <span class="align-middle">DMS</span>
        </a>

        <ul class="sidebar-nav">
            <li class="sidebar-header">
                Pages
            </li>

            <li class="sidebar-item active">
                <a class="sidebar-link" href="{% url 'document:create_document_view' %}">
                    <i class="align-middle" data-feather="plus-circle"></i> <span class="align-middle">Add Document</span>
                </a>
            </li>
            
            <li class="sidebar-item">
                <a class="sidebar-link" href="{% url 'document:document_view' %}">
                    <i class="align-middle" data-feather="folder"></i>
                    <span class="align-middle">Document</span>
                </a>
            </li>
            <li class="sidebar-item">
                <a class="sidebar-link" href="{% url 'document:employee_assignment_view' %}">
                    <i class="align-middle" data-feather="users"></i> <span class="align-middle">Group
                        Assignment</span>
                </a>
            </li>
            {% if user.type == user.Types.MANAGER %}
                <li class="sidebar-item">
                    <a class="sidebar-link" href="{% url 'document:all_document' %}">
                        <i class="align-middle" data-feather="folder"></i> <span class="align-middle">All
                            Document</span>
                    </a>
                </li>
                <li class="sidebar-item">
                    <a class="sidebar-link" href="{% url 'document:public_document' %}">
                        <i class="align-middle" data-feather="folder"></i> <span class="align-middle">Public
                            Document</span>
                    </a>
                </li>
                <li class="sidebar-item">
                    <a class="sidebar-link" href="{% url 'document:private_document' %}">
                        <i class="align-middle" data-feather="lock"></i> <span class="align-middle">Private
                            Document</span>
                    </a>
                </li>
                <li class="sidebar-item">
                    <a class="sidebar-link" href="{% url 'document:group_assignment_view' %}">
                        <i class="align-middle" data-feather="users"></i> <span class="align-middle">Add Group
                            Assignment</span>
                    </a>
                </li>
                <li class="sidebar-item">
                    <a class="sidebar-link" href="{% url 'document:group_assignment_list_view' %}">
                        <i class="align-middle" data-feather="users"></i> <span class="align-middle">Group
                            Assignment List</span>
                    </a>
                </li>
            {% endif %}
            
            {% if user.is_staff %}
                <li class="sidebar-item">
                    <a class="sidebar-link" href="{% url 'account:all_user_view' %}">
                        <i class="align-middle" data-feather="users"></i>
                        <span class="align-middle">All User</span>
                    </a>
                </li>
            {% endif %}
                
        </ul>
    </div>
</nav>