document_management_system/document_management_system/core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('accounts.urls', namespace='account')),
    path('', include('documents.urls', namespace='document')),
   

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

'''
template_name='account/password_reset.html'
template_name='account/password_reset_done.html'
template_name='account/password_reset_confirm.html'
template_name='account/password_reset_complete.html'
path('password_change/', auth_views.PasswordChangeView.as_view(),
        name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(),
        name='password_change_done'),

    path('password_reset/', auth_views.PasswordResetView.as_view(),
        name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(),
        name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),
        name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(),
        name='password_reset_complete'),
'''

document_management_system/document_management_system/documents/urls.py
from django.urls import path
from documents.views import (
    LandingView,
    public_document_view,
    private_document_view,
    user_create_document_view,
    employee_document_view,
    create_group_assignment,
    group_assignment_list,
    employee_group_assignment,
    update_document_view,
    AllDocumentView,
    delete_document_view,
    delete_group_assignment,
    update_group_assignment,
    search_view,
)

app_name = 'documents'
urlpatterns = [
    path('', LandingView.as_view(), name='home'),
    path('all-document/', AllDocumentView.as_view(), name='all_document'),
    path('create-document/', user_create_document_view, name='create_document_view'),
    path('public-document/', public_document_view, name='public_document'),
    path('private-document/', private_document_view, name='private_document'),
    path('document/', employee_document_view, name='document_view'),
    path('create-group-assignment/', create_group_assignment, name='group_assignment_view'),
    path('group-assignment-list/', group_assignment_list, name='group_assignment_list_view'),
    path('employee-assignment/', employee_group_assignment, name='employee_assignment_view'),
    path('update-document/<int:pk>/', update_document_view, name='update_document_view'),
    path('delete-document/<int:pk>/', delete_document_view, name='delete_document'),
    path('delete-group-assignment/<slug:slug>/', delete_group_assignment, name='delete_group_assigment'),
    path('update-group-assignment/<slug:slug>/', update_group_assignment, name='update_group_assignment'),
     path('search/', search_view, name='search_view'),
]

document_management_system/document_management_system/documents/models.py
from django.db import models
from django.conf import settings


class PublicDocumentManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status='PUBLIC')

class PrivateDocumentManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status='PRIVATE')

STATUS_CHOICES = (
    ('PUBLIC', 'Public'),
    ('PRIVATE', 'Private')
)

class Document(models.Model):
    user                = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title               = models.CharField(max_length=255)
    document            = models.FileField(upload_to='document/')
    status              = models.CharField(max_length=10, choices=STATUS_CHOICES, default='PUBLIC')
    created_at          = models.DateTimeField(auto_now_add=True)
    updated_at          = models.DateTimeField(auto_now=True)

    objects             = models.Manager() # default manager
    public_manager      = PublicDocumentManager() # custom publice manager
    private_manager     = PrivateDocumentManager() # custom private manager    


    def __str__(self):
        return f'{self.title}-#{self.user}'

# group assignment 
class GroupAssignment(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(unique=True, blank=True)
    member = models.ManyToManyField(settings.AUTH_USER_MODEL, verbose_name=("Group User"))
    document = models.ManyToManyField(Document, verbose_name=("Group Document"))
    created_at          = models.DateTimeField(auto_now_add=True)
    updated_at          = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

document_management_system/document_management_system/documents/forms.py
from django import forms
from .models import Document, GroupAssignment

class DocumentForm(forms.ModelForm):
    class Meta:
        model = Document
        fields = ('title', 'document')

class UpdateDocumentForm(forms.ModelForm):
    class Meta:
        model = Document
        fields = ('__all__')
class UpdateGroupAssignmentForm(forms.ModelForm):
    class Meta:
        model = GroupAssignment
        fields = ('__all__')

class GroupAssignmentForm(forms.ModelForm):
    class Meta:
        model = GroupAssignment
        fields = ('name', 'document', 'member')
        widgets = {
            'document': forms.CheckboxSelectMultiple(attrs={'calss': 'form-control'}),
            'member': forms.CheckboxSelectMultiple(attrs={'calss': 'form-control'}),
        }

document_management_system/document_management_system/documents/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import TemplateView, ListView
from django.contrib.auth.decorators import login_required
from accounts.models import Account
from .models import Document, GroupAssignment
from .forms import (
    DocumentForm,
    GroupAssignmentForm,
    UpdateDocumentForm,
    UpdateGroupAssignmentForm,
)
from django.db.models import Q
class LandingView(TemplateView):
    template_name = 'landing.html'

class AllDocumentView(ListView):
    model = Document
    template_name = 'document/all-document.html'

@login_required
def user_create_document_view(request):
    form = DocumentForm()
    if request.method == 'POST':
        form = DocumentForm(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.user = request.user 
            instance.save()
            return redirect('document:document_view')
    else:
        form = DocumentForm()
    template_name = 'document/document-form.html'
    context = {'form': form}
    return render(request, template_name, context)

@login_required
def create_group_assignment(request):
    form = GroupAssignmentForm()
    if request.method == 'POST':
        form = GroupAssignmentForm(request.POST or None)
        if form.is_valid():
            form.save()
            return redirect('document:group_assignment_list_view')
    else:
        form = GroupAssignmentForm()
    template_name = 'document/create-group-assignment.html'
    context = {'form': form} 
    return render(request, template_name, context)

@login_required
def delete_group_assignment(request, slug):
    ga = get_object_or_404(GroupAssignment, slug=slug)
    ga.delete()
    return redirect('document:group_assignment_list_view')

@login_required
def update_group_assignment(request, slug):
    uga = get_object_or_404(GroupAssignment, slug=slug)
    form = UpdateGroupAssignmentForm(request.POST or None, instance=uga)
    if form.is_valid():
        form.save()
        return redirect('document:group_assignment_list_view')
    template_name = 'document/update-group-assignment.html'
    context = {
        'form': form,
    }
    return render(request, template_name, context)

@login_required
def group_assignment_list(request):
    group_assignment = GroupAssignment.objects.all()
    template_name = 'document/group-assignment-list.html'
    context = {'group_assignment': group_assignment} 
    return render(request, template_name, context)

@login_required
def employee_document_view(request):
    user = request.user
    document = Document.objects.filter(user=user)
    template_name = 'document/employee-document.html'
    context = {'document': document,}
    return render(request, template_name, context)

@login_required
def employee_group_assignment(request):
    user= request.user
    assignment =  GroupAssignment.objects.filter(member=user)
    template_name = 'document/employee-assignment.html'
    context = {'assignment': assignment,}
    return render(request, template_name, context)

@login_required
def public_document_view(request):
    public_document = Document.public_manager.all()
    template_name = 'document/public-document.html'
    context = {'public_document': public_document,}
    return render(request, template_name, context)
    
@login_required
def private_document_view(request):
    private_document = Document.private_manager.all()
    template_name = 'document/private-document.html'
    context = {'private_document': private_document}
    return render(request, template_name, context)

@login_required
def update_document_view(request, pk):
    document = get_object_or_404(Document, pk=pk)
    form = UpdateDocumentForm(request.POST or None, instance=document)
    if form.is_valid():
        form.save()
        return redirect('document:document_view')
    template_name = 'document/update-document.html'
    context = {'form': form,}
    return render(request, template_name, context)

@login_required
def delete_document_view(request, pk):
    document = get_object_or_404(Document, pk=pk)
    document.delete()
    return redirect('document:all_document')
    
@login_required
def search_view(request):
    document = Document.public_manager.all()
    search = request.GET.get('q')
    if search:
        document = document.filter(
            Q(title__icontains=search)
        )
    template_name = 'document/search-document.html'
    context = {'document': document}
    return render(request, template_name, context)

document_management_system/document_management_system/templates/document/all-document.html
<!-- Export base.html file -->
{% extends 'base.html' %}
<!-- static file load -->
{% load static %}
<!-- header title -->
{% block head_title %}public-document{% endblock head_title %}

<!-- main content -->
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-12 col-xl-10 m-auto">
                <div class="card mt-3">
                    <div class="card-header">
                        <h5 class="card-title">Contextual Classes</h5>
                        <h6 class="card-subtitle text-muted">Use contextual classes to color table rows or individual cells.</h6>
                    </div>
                    <table class="table">
                        <thead>
                            <tr>
                                <th style="width:40%;">Title</th>
                                <th style="width:25%">File</th>
                                <th class="d-none d-md-table-cell" style="width:25%">Upload Date</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            
                            {% for object in object_list %}
                                <tr>
                                    <td>{{ object.title }}</td>
                                    <td class="d-none d-md-table-cell">{{ object.document }}</td>
                                    <td>
                                        {{ object.created_at }}
                                    </td>
                                    <td class="table-action">
                                        <a href="{% url 'document:update_document_view' pk=object.pk %}"><i class="align-middle" data-feather="edit-2"></i></a>
                                        <a href="{% url 'document:delete_document' pk=object.pk %}"><i class="align-middle" data-feather="trash"></i></a>
                                    </td>
                                </tr>
                            {% endfor %}
                                
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

document_management_system/document_management_system/templates/document/create-group-assignment.html
<!-- Export base.html file -->
{% extends 'base.html' %}
<!-- static file load -->
{% load static %}
<!-- header title -->
{% block head_title %}add-document{% endblock head_title %}

<!-- main content -->
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-xl-6 m-auto">
                <div class="card mt-5">
                    <div class="card-header">
                        <h3 class="card-subtitle text-muted m-2 text-center">Document management system</h3>
                    </div>
                    <div class="card-body">
                        <form action="" method="POST" enctype='multipart/form-data'>
                            {% csrf_token %}
                            {{ form.as_p }}
                            <!-- <input type="text" name="title" class="form-control mb-3" placeholder="Document title">
                            <input type="file" name="document" class="form-control mb-3"> -->
                            <button type="submit" class="btn btn-primary">Submit</button>
                            {% for field in form %}
                            <p>
                                {% for error in field.errors %}
                                    <p style="color: red;">{{ error }}</p>
                                {% endfor %}   
                            </p>
                            {% endfor %}
                            {% if form.non_field_errors %}
                                <p style="color: red;">{{ form.non_field_errors }}</p>
                            {% endif %}
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

document_management_system/document_management_system/templates/document/document-form.html
<!-- Export base.html file -->
{% extends 'base.html' %}
<!-- static file load -->
{% load static %}
<!-- header title -->
{% block head_title %}add-document{% endblock head_title %}

<!-- main content -->
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-xl-6 m-auto">
                <div class="card mt-5">
                    <div class="card-header">
                        <h3 class="card-subtitle text-muted m-2 text-center">Document management system</h3>
                    </div>
                    <div class="card-body">
                        <form action="" method="POST" enctype='multipart/form-data'>
                            {% csrf_token %}
                            <input type="text" name="title" class="form-control mb-3" placeholder="Document title">
                            <input type="file" name="document" class="form-control mb-3">
                            <button type="submit" class="btn btn-primary">Submit</button>
                            {% for field in form %}
                            <p>
                                {% for error in field.errors %}
                                    <p style="color: red;">{{ error }}</p>
                                {% endfor %}   
                            </p>
                            {% endfor %}
                            {% if form.non_field_errors %}
                                <p style="color: red;">{{ form.non_field_errors }}</p>
                            {% endif %}
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

document_management_system/document_management_system/templates/document/employee-assignment.html
<!-- Export base.html file -->
{% extends 'base.html' %}
<!-- static file load -->
{% load static %}
<!-- header title -->
{% block head_title %}public-document{% endblock head_title %}

<!-- main content -->
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-12 col-xl-10 m-auto">
                <div class="card mt-3">
                    <div class="card-header">
                        <h5 class="card-title">Contextual Classes</h5>
                        <h6 class="card-subtitle text-muted">Use contextual classes to color table rows or individual cells.</h6>
                    </div>
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Title</th>
                                <th>File</th>
                                <th>Upload Date</th>
                            </tr>
                        </thead>
                        <tbody>
                            
                            {% for obj in assignment %}
                                <tr>
                                    <td>{{ obj.name }}</td>
                                    <td>
                                        <ul>
                                        {% for u in obj.member.all %}
                                                <li>{{ u.username }}</li>
                                        {% endfor %}
                                    </ul>
                                            
                                    </td>
                                    <td>
                                        <ul>
                                            {% for d in obj.document.all %}
                                                <li>{{ d.title }}</li>
                                            {% endfor %}
                                        </ul>
                                    </td>
                                    <td>{{ obj.created_at|date:"M d, Y" }}</td>
                                </tr>
                            {% empty %}
                                <tr>
                                    <td colspan="3"><h4 class="text-center">Sorry.......</h4></td>
                                </tr>
                            {% endfor %}
                                
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

document_management_system/document_management_system/templates/document/employee-document.html
<!-- Export base.html file -->
{% extends 'base.html' %}
<!-- static file load -->
{% load static %}
<!-- header title -->
{% block head_title %}public-document{% endblock head_title %}

<!-- main content -->
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-12 col-xl-10 m-auto">
                <div class="card mt-3">
                    <div class="card-header">
                        <h5 class="card-title">Contextual Classes</h5>
                        <h6 class="card-subtitle text-muted">Use contextual classes to color table rows or individual cells.</h6>
                    </div>
                    <table class="table">
                        <thead>
                            <tr>
                                <th style="width:40%;">Title</th>
                                <th style="width:25%">File</th>
                                <th class="d-none d-md-table-cell" style="width:25%">Date of Birth</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            
                            {% for d in document.all %}
                                <tr>
                                    <td>{{ d.title }}</td>
                                    <td class="d-none d-md-table-cell">{{ d.document }}</td>
                                    <td>
                                        {{ d.created_at }}
                                    </td>
                                    <td class="table-action">
                                        <a href="#"><i class="align-middle" data-feather="edit-2"></i></a>
                                        <a href="#"><i class="align-middle" data-feather="trash"></i></a>
                                    </td>
                                </tr>
                            {% endfor %}
                                
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

document_management_system/document_management_system/templates/document/group-assignment-list.html
<!-- Export base.html file -->
{% extends 'base.html' %}
<!-- static file load -->
{% load static %}
<!-- header title -->
{% block head_title %}public-document{% endblock head_title %}

<!-- main content -->
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-12 col-xl-12 m-auto">
                <div class="card mt-3">
                    <div class="card-header">
                        <h5 class="card-title">Contextual Classes</h5>
                        <h6 class="card-subtitle text-muted">Use contextual classes to color table rows or individual cells.</h6>
                    </div>
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Phone Number</th>
                                <th>Upload Date</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            
                            {% for obj in group_assignment %}
                                <tr>
                                    <td>{{ obj.name }}</td>
                                    <td>{{ obj.member }}</td>
                                    <td>{{ obj.document }}</td>
                                    <td>{{ obj.created_at }}</td>
                                    <td class="table-action">
                                        <a href="{% url 'document:update_group_assignment' slug=obj.slug %}"><i class="align-middle" data-feather="edit-2"></i></a>
                                        <a href="{% url 'document:delete_group_assigment' slug=obj.slug %}"><i class="align-middle" data-feather="trash"></i></a>
                                    </td>
                                </tr>
                            {% endfor %}
                                
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

document_management_system/document_management_system/templates/document/private-document.html
<!-- Export base.html file -->
{% extends 'base.html' %}
<!-- static file load -->
{% load static %}
<!-- header title -->
{% block head_title %}public-document{% endblock head_title %}

<!-- main content -->
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-12 col-xl-10 m-auto">
                <div class="card mt-3">
                    <div class="card-header">
                        <h5 class="card-title">Contextual Classes</h5>
                        <h6 class="card-subtitle text-muted">Use contextual classes to color table rows or individual cells.</h6>
                    </div>
                    <table class="table">
                        <thead>
                            <tr>
                                <th>User</th>
                                <th>title</th>
                                <th>Document</th>
                                <th>status</th>
                                <th>Join Date</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            
                            {% for pd in private_document %}
                                <tr>
                                    <td>{{ pd.user }}</td>
                                    <td>{{ pd.title }}</td>
                                    <td>{{ pd.document }}</td>
                                    <td>{{ pd.status }}</td>
                                    <td>{{ pd.created_at|date }}</td>
                                    <td class="table-action">
                                        <a href="#"><i class="align-middle" data-feather="edit-2"></i></a>
                                        <a href="#"><i class="align-middle" data-feather="trash"></i></a>
                                    </td>
                                </tr>
                            {% endfor %}
                                
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

document_management_system/document_management_system/templates/document/public-document.html
<!-- Export base.html file -->
{% extends 'base.html' %}
<!-- static file load -->
{% load static %}
<!-- header title -->
{% block head_title %}public-document{% endblock head_title %}

<!-- main content -->
{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-12 col-xl-10 m-auto">
                <div class="card mt-3">
                    <div class="card-header">
                        <h5 class="card-title">Contextual Classes</h5>
                        <h6 class="card-subtitle text-muted">Use contextual classes to color table rows or individual cells.</h6>
                    </div>
                    <table class="table">
                        <thead>
                            <tr>
                                <th>User</th>
                                <th>Title</th>
                                <th>Document</th>
                                <th>status</th>
                                <th>Join date</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            
                            {% for pd in public_document %}
                                <tr>
                                    <td>{{ pd.user }}</td>
                                    <td>{{ pd.title }}</td>
                                    <td>{{ pd.document }}</td>
                                    <td>{{ pd.status }}</td>
                                    <td>{{ pd.created_at|date }}</td>
                                    <td class="table-action">
                                        <a href="#"><i class="align-middle" data-feather="edit-2"></i></a>
                                        <a href="#"><i class="align-middle" data-feather="trash"></i></a>
                                    </td>
                                </tr>
                            {% endfor %}
                                
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

document_management_system/document_management_system/templates/document/search-document.html
<!-- Export base.html file -->
{% extends 'base.html' %}
<!-- static file load -->
{% load static %}
<!-- header title -->
{% block head_title %}search-document{% endblock head_title %}

<!-- main content -->
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-12 col-xl-10 m-auto">
                <div class="card mt-3">
                    <div class="card-header">
                        <h5 class="card-title">Contextual Classes</h5>
                        <h6 class="card-subtitle text-muted">Use contextual classes to color table rows or individual cells.</h6>
                    </div>
                    <table class="table">
                        <thead>
                            <tr>
                                <th style="width:40%;">Title</th>
                                <th style="width:25%">File</th>
                                <th class="d-none d-md-table-cell" style="width:25%">Date of Birth</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            
                            {% for object in document %}
                                <tr>
                                    <td>{{ object.title }}</td>
                                    <td class="d-none d-md-table-cell">{{ object.document }}</td>
                                    <td>
                                        {{ object.created_at|date }}
                                    </td>
                                </tr>
                            {% endfor %}
                                
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

document_management_system/document_management_system/templates/document/update-document.html
<!-- Export base.html file -->
{% extends 'base.html' %}
<!-- static file load -->
{% load static %}
<!-- header title -->
{% block head_title %}add-document{% endblock head_title %}

<!-- main content -->
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-xl-6 m-auto">
                <div class="card mt-5">
                    <div class="card-header">
                        <h3 class="card-subtitle text-muted m-2 text-center">Document management system</h3>
                    </div>
                    <div class="card-body">
                        <form action="" method="POST" enctype='multipart/form-data'>
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-primary">Submit</button>
                            {% for field in form %}
                            <p>
                                {% for error in field.errors %}
                                    <p style="color: red;">{{ error }}</p>
                                {% endfor %}   
                            </p>
                            {% endfor %}
                            {% if form.non_field_errors %}
                                <p style="color: red;">{{ form.non_field_errors }}</p>
                            {% endif %}
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}