document_management_system/document_management_system/accounts/urls.py
from django.urls import path,include
from django.contrib.auth import views as auth_views
from .forms import PwdResetConfirmForm, PwdResetForm
from django.views.generic import TemplateView
from .views import (
    deshboard_page_view,
    employee_register_view,
    manager_register_view,
    user_login_view,
    user_logout_view,
    all_user_view,
    register_all_view,
    user_update_view,
    user_delete_view,
    user_profile_update,
    user_profile_view,
)

app_name = 'accounts'
urlpatterns = [
    path('dashboard/', deshboard_page_view, name='dashboard_view'),
    path('register-all_view/', register_all_view, name='register_all_view'),
    path('register/', employee_register_view, name='register_view'),
    path('manager-register/', manager_register_view, name='manager_register_view'),
    path('login/', user_login_view, name='login_view'),
    path('logout/', user_logout_view, name='logout_view'),
    path('all-user/', all_user_view, name='all_user_view'),
    path('user-update/<int:pk>/', user_update_view, name='user_update_view'),
    path('user-delete/<int:pk>/', user_delete_view, name='user_delete'),
    path('user-update/<int:pk>/', user_update_view, name='user_update_view'),
    path('user-delete/<int:pk>/', user_delete_view, name='user_delete'),


    # password reset
    path(
        "password_reset/",
        auth_views.PasswordResetView.as_view(
            template_name="account/password_reset/password_reset_form.html",
            success_url="password_reset_email_confirm",
            email_template_name="account/password_reset/password_reset_email.html",
            form_class=PwdResetForm,
        ),
        name="pwdreset",
    ),
    path(
        "password_reset_confirm/<uidb64>/<token>",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="account/password_reset/password_reset_confirm.html",
            success_url="password_reset_complete/",
            form_class=PwdResetConfirmForm,
        ),
        name="password_reset_confirm",
    ),
    path(
        "password_reset/password_reset_email_confirm/",
        TemplateView.as_view(template_name="account/password_reset/reset_status.html"),
        name="password_reset_done",
    ),
    path(
        "password_reset_confirm/Mg/password_reset_complete/",
        TemplateView.as_view(template_name="account/password_reset/reset_status.html"),
        name="password_reset_complete",
    ),
]

document_management_system/document_management_system/core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('accounts.urls', namespace='account')),
    path('', include('documents.urls', namespace='document')),
   

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

'''
template_name='account/password_reset.html'
template_name='account/password_reset_done.html'
template_name='account/password_reset_confirm.html'
template_name='account/password_reset_complete.html'
path('password_change/', auth_views.PasswordChangeView.as_view(),
        name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(),
        name='password_change_done'),

    path('password_reset/', auth_views.PasswordResetView.as_view(),
        name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(),
        name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),
        name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(),
        name='password_reset_complete'),
'''

document_management_system/document_management_system/templates/all register.html
{% load static %}





<title>select type register</title>
<!-- Required meta tags -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<!-- Font Awesome icons (free version)-->
<script src="https://use.fontawesome.com/releases/v5.15.1/js/all.js" crossorigin="anonymous"></script>
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body class="bg-dark text-white">    
<div class="container-fluid">
    <div class="row">
        <br><br><br><br><br><br><br><br><br><br><br><br><br>
        
    </div>
</div>
<div class="container-fluid">
  <div class="row">
      

                    <div class="col align-self-center "> <a href="{% url 'account:login_view' %}"> <div class="p-2  display-1 text-center "><i class="fas fa-user "></i> </div></a>
                        
                        <p class="text-center">Admin</p>
                        
                    </div>
                    <div class="col"> <a href="{% url 'account:register_view' %}"> <div class="p-2 text-center display-1"><i class="fas fa-user "></i> </div></a>
                    <p class="text-center">Employee</p>
                            </div>
                    <div class="col"> <a href="{% url 'account:manager_register_view' %}"> <div class="p-2  text-center display-1"><i class="fas fa-user "></i> </div></a>
                    <p class="text-center">Manager</p>
       
                    </div>                     
    
  </div>
</div>
   
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

document_management_system/document_management_system/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="description" content="Responsive Web UI Kit &amp; Dashboard Template based on Bootstrap">
	<meta name="author" content="AdminKit">
	<meta name="keywords" content="adminkit, bootstrap, web ui kit, dashboard template, admin template">

	<link rel="shortcut icon" href="img/icons/icon-48x48.png" />

	<title>{% block head_title %}{% endblock head_title %} | Document Management System</title>

	<link href="{% static 'css/app.css' %}" rel="stylesheet">
</head>

<body>
    <div class="wrapper">
        {% include 'snippets/sidebar-navbar.html' %}
        <div class="main">
            {% include 'snippets/navbar.html' %}
			<main class="content" style="min-height: 100vh; height: 100%;">
            {% block content %}
            {% endblock content %}
			</main>
            {% include 'snippets/footer.html' %}
	    </div>
    </div>
    <!-- bootstrap javascript -->
	<script src="{% static 'js/vendor.js' %}"></script>
	<script src="{% static 'js/app.js' %}"></script>
	<script>
		$(function() {
			$('#datetimepicker-dashboard').datetimepicker({
				inline: true,
				sideBySide: false,
				format: 'L'
			});
		});
	</script>

</body>

</html>

document_management_system/document_management_system/templates/base1.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="description" content="Responsive Web UI Kit &amp; Dashboard Template based on Bootstrap">
	<meta name="author" content="AdminKit">
	<meta name="keywords" content="adminkit, bootstrap, web ui kit, dashboard template, admin template">

	<link rel="shortcut icon" href="img/icons/icon-48x48.png" />

	<title>{% block head_title %}{% endblock head_title %} | Document Management System</title>

	<link href="{% static 'css/app.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>

<body>
    <div class="wrapper">
        <div class="main">
            {% include 'snippets/home-navbar.html' %}
            <div class="main-content" style="min-height: 100vh; height: 100%;">
                {% block content %}
                {% endblock content %}
            </div>
            {% include 'snippets/footer.html' %}
	    </div>
    </div>
    <!-- bootstrap javascript -->
	<script src="{% static 'js/vendor.js' %}"></script>
	<script src="{% static 'js/app.js' %}"></script>
	<script>
		$(function() {
			$('#datetimepicker-dashboard').datetimepicker({
				inline: true,
				sideBySide: false,
				format: 'L'
			});
		});
	</script>

</body>

</html>

document_management_system/document_management_system/templates/landing.html
{% extends 'base1.html' %}
<!-- static file load -->
{% load static %}
<!-- header title -->
{% block head_title %}Login{% endblock head_title %}

<!-- main content -->
{% block content %}
<!DOCTYPE html>
<html lang="en">
    {% load static%}
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Landing page</title>
        <link rel="icon" type="image/x-icon" href="assets/img/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.15.1/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'new/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body id="page-top">
        <!-- Navigation-->
       
           <!-- Masthead-->
           <div class="jumbotron jumbotron-fluid bg-dark vh-50">
            <div class="container text-center text-white ">
                <br><br><br>
                  
              <h2>Welcome to Plan International</h2><br>
              <p>Thank you for visiting our page</p> <br>
              <button type="button" class="btn btn-secondary"><a href="#services">Login to visit </a></button>
              <!-- <a class="btn btn-primary btn-xl text-uppercase js-scroll-trigger" href="#services">Tell Me More</a> -->
            </div>
          </div>
                
            
        </header>
        <!-- Services-->
        
        
        
        <!-- Team-->
        <section class="page-section bg-light" id="team">
            <div class="container">
                <div class="text-center">
                    <h2 class="section-heading text-uppercase">Our Team</h2>
                   
                </div>
                <div class="row">
                    <div class="col-lg-4">
                        <div class="team-member">
                            <img class="mx-auto rounded-circle" src="{% static 'new/assets/img/team/akib.jpg'%}" alt="" />
                            <h4>Akib dewan</h4>
                            <p class="text-muted"></p>
                            <a class="btn btn-dark btn-social mx-2" href="#!"><i class="fab fa-twitter"></i></a>
                            <a class="btn btn-dark btn-social mx-2" href="#!"><i class="fab fa-facebook-f"></i></a>
                            <a class="btn btn-dark btn-social mx-2" href="#!"><i class="fab fa-linkedin-in"></i></a>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="team-member">
                            <img class="mx-auto rounded-circle" src="{% static 'new/assets/img/team/ali.jpg'%}" alt="" />
                            <h4>Ali hawk</h4>
                            <p class="text-muted"></p>
                            <a class="btn btn-dark btn-social mx-2" href="#!"><i class="fab fa-twitter"></i></a>
                            <a class="btn btn-dark btn-social mx-2" href="#!"><i class="fab fa-facebook-f"></i></a>
                            <a class="btn btn-dark btn-social mx-2" href="#!"><i class="fab fa-linkedin-in"></i></a>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="team-member">
                            
                            <img class="mx-auto rounded-circle" src="{% static 'new/assets/img/team/tanvir.png'%}" alt="" />
                            <h4>tanvir sadat</h4>
                            <p class="text-muted"></p>
                            <a class="btn btn-dark btn-social mx-2" href="#!"><i class="fab fa-twitter"></i></a>
                            <a class="btn btn-dark btn-social mx-2" href="#!"><i class="fab fa-facebook-f"></i></a>
                            <a class="btn btn-dark btn-social mx-2" href="#!"><i class="fab fa-linkedin-in"></i></a>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="team-member">
                            
                            <img class="mx-auto rounded-circle" src="{% static 'new/assets/img/team/sujana.png'%}" alt="" />
                            <h4>Kazi Sarat Islam </h4>
                            <p class="text-muted"></p>
                            <a class="btn btn-dark btn-social mx-2" href="#!"><i class="fab fa-twitter"></i></a>
                            <a class="btn btn-dark btn-social mx-2" href="#!"><i class="fab fa-facebook-f"></i></a>
                            <a class="btn btn-dark btn-social mx-2" href="#!"><i class="fab fa-linkedin-in"></i></a>
                        </div>
                    </div>
                </div>
                <div class="row">
                
                </div>
            </div>
        </section>
       
        
      
       
    </body>
</html>
{% endblock content %}

document_management_system/document_management_system/templates/simple.html
<!-- Export base.html file -->
{% extends 'base.html' %}
<!-- static file load -->
{% load static %}
<!-- header title -->
{% block head_title %}{% endblock head_title %}

<!-- main content -->
{% block content %}
        
{% endblock content %}